"""Initial migration

Revision ID: 51c1b7f357ca
Revises: 89288b6d1695
Create Date: 2024-09-28 20:40:19.476106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51c1b7f357ca'
down_revision = '89288b6d1695'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercise', schema=None) as batch_op:

    # ### end Alembic commands ###


def downgrade():
    with op.batch_alter_table('exercise', schema=None) as batch_op:
        batch_op.create_index('ix_exercise_id', ['id'], unique=False)


    # ### end Alembic commands ###
